# Generated by Django 3.2 on 2021-05-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prilozhenie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
